### ISSUE TITLE
انتقال webapi به لایه IDP

### ISSUE THREAD

**Issue by hofa77** [VahidN/IdentityServerImageGallery#1]
سلام جناب نصیری

اگر بخواهیم لایه
 webapi
را به همون لایه 
IDP 
انتقال بدیم ، و بخواهیم یکسری 
api 
عمومی سایت فقط 
Aud 
چک بشه  
چه تغییری باید داده بشه ؟

تشکر فراوان

**Comment by VahidN** [comment]
<div dir="rtl">

IDP يك لايه نيست. يك برنامه‌ي كاملا مستقل هست.  هدف اصلي آن هم همين مستقل بودن و نقش تامين هويت مركزي را بازي كردن هست و گرنه اگر قرار باشد اين‌ها با هم يكي شوند، شايد بهتر باشد از ASP.NET Core Identity استفاده كنيد.
توضيح اين مسايل خارج است از حوصله‌ي اين مخزن كد. [جايي ديگري توضيح داده شده](https://www.dotnettips.info/learningpaths/details/75)

**Comment by hofa77** [comment]
ببخشید این سوال رو ادامه میدم
متوجه منظورتون هستم
نکته اینه که یک سایت که دارای سه کلاینت انگیولار ، اندروید و آی او اس است 
اگر بتونیم در همین کدهای شما تغییراتی ایجاد کنیم که لازم نباشه دوتا دیتابیس ایجاد بشه ، و یا مجبور بشیم سیستم 
IDP 
 بره در زیر دامنه ، برای سیستم های کوچیک راحت تره
من کاملا متوجه جامعیت 
IdentityService 
هستم
ولی بهرحال برای سیستم های کوچیک اگر بشه
 webapi
 رو برد در دل
 IDP
 مدیریتش رو ساده تر میکنه بنظرم
اگر مقاله خاصی در جایی نوشتید یا میدونید معرفی کنید 
بینهایت ممنون میشم

**Comment by VahidN** [comment]
<div dir="rtl">

شما فقط سه رابط كاربري مختلف را براي يك سيستم داريد. سناريوي شما نيازي به IDP ندارد. كار شما يك برنامه‌ي متداول است و اين سه كلاينت‌ سه برنامه‌ي مجزا به حساب نمي‌آيند چون در نهايت با يك سيستم قرار است كار كنند. در اينجا بهتر است از ASP.NET Core Identity استفاده كنيد و به خوبي كلاينت‌هاي شما را پوشش مي‌دهد. هم از روش كوكي‌ها و هم از روش JWT با هم پشتيباني مي‌كند و براي كار شما كافي است.
اگر فقط يك سايت را داريد، اينكار براي شما مناسب نيست.
اگر فقط يك برنامه‌ي back-end را داريد اين روش براي شما مناسب نيست.
اين روش براي شركتي طراحي شده كه يك برنامه‌ي حسابداري دارد،‌ يك برنامه‌ي مجزاي منابع انساني و مديريت كارمندان، يك برنامه‌ي مجزاي مالي و حقوق و دستمزد، يك برنامه‌ي مجزاي حضور و غياب، يك برنامه‌ي مجزاي اعلانات شركت و غيره. هر كدام از اين برنامه‌ها هم يك ديتابيس مستقل دارند. اينجا است كه IDP معنا پيدا مي‌كند. 
اما اگر كل كار شما فقط يك برنامه‌ي back-end را به همراه فقط يك ديتابيس دارد، اين روش اصلا مناسب كار شما نيست و از همان روش ASP.NET Core Identity متداول استفاده كنيد كه دقيقا براي همين منظور طراحي شده‌است.

**Comment by hofa77** [comment]
تشکر فراوان
