### ISSUE TITLE
خطا در زمان اجرا IDX20803

### ISSUE THREAD

**Issue by saeedrahmo** [VahidN/IdentityServerImageGallery#2]
`An unhandled exception occurred while processing the request.
InvalidOperationException: IDX20803: Unable to obtain configuration from: 'https://localhost:6001/.well-known/openid-configuration'.
Microsoft.IdentityModel.Protocols.ConfigurationManager<T>.GetConfigurationAsync(CancellationToken cancel)`

**Comment by VahidN** [comment]
<div dir="rtl">

اين دو مطلب را مطالعه كنيد؛ خصوصا مورد اول را
-  [تنظیم مجوز امضای توکن‌های IDP](https://www.dotnettips.info/post/2917) 
-  [اجبار به استفاده‌ی از HTTPS در حین توسعه‌ی برنامه‌های ASP.NET Core 2.1](https://www.dotnettips.info/post/2831)
